version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      # Stay on React 18 types until we intentionally upgrade React to 19
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
