services:
  db:
    image: postgres:15-alpine
    container_name: itam-postgres
    environment:
      POSTGRES_DB: asset_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    image: itam-backend:local
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/asset_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: itam-frontend:local
    environment:
      - BACKEND_ORIGIN=http://backend:8080
    ports:
      - "3001:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
