spring:
  profiles:
    active: dev
  
  application:
    name: IT Asset Management System
    version: 1.0.0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    cors:
      allowed-origins: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3006,http://127.0.0.1:3006"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: it-asset-management
      environment: ${SPRING_PROFILES_ACTIVE:dev}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.chaseelkins.assetmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.cors: DEBUG

# JWT Configuration
jwt:
  # In production supply via environment: export JWT_SECRET=... (length >= 32 chars)
  secret: "${JWT_SECRET:mySecretKey123456789012345678901234567890}"
  # Legacy property (will be superseded by access-expiration if present)
  expiration: 86400000 # 24 hours in milliseconds (fallback)
  # New granular expirations
  access-expiration: 900000      # 15 minutes
  refresh-expiration: 604800000  # 7 days

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: IT Asset Management System API
    description: RESTful API for managing IT assets, users, and maintenance records
    version: 1.0.0
    contact:
      name: Chase Elkins
      email: chase@example.com

# Custom Application Properties
app:
  name: IT Asset Management System
  description: Full-stack application for IT asset tracking
  version: 1.0.0
  contact:
    name: Chase Elkins
    email: chase@example.com
