import { app, BrowserWindow, ipcMain } from 'electron';
import { join } from 'path';
import { initDatabase } from './database/db';
import { setupCategoryHandlers } from './ipc/categories';
import { setupAssetHandlers } from './ipc/assets';
import { setupCustomFieldHandlers } from './ipc/customFields';
import { setupInventoryItemHandlers } from './ipc/inventoryItems';
import { setupAssignmentHandlers } from './ipc/assignments';
import { setupActivityLogHandlers } from './ipc/activityLog';
import { setupMaintenanceHandlers, scheduleAutomaticOptimization } from './ipc/maintenance';
import { setupSettingsHandlers } from './ipc/settings';
import { setupInventoryTransactionHandlers } from './ipc/inventoryTransactions';
import { setupBusinessProfileHandlers } from './ipc/businessProfile';
import { setupCategoryPreferenceHandlers } from './ipc/categoryPreferences';
import { setupQRCodeHandlers } from './ipc/qrCodes';
import { setupFilterPresetHandlers } from './ipc/filterPresets';
import { setupAuthHandlers } from './ipc/auth';
import { setupAttachmentHandlers } from './ipc/attachments';
import { setupBarcodeHandlers } from './ipc/barcodes';
import { setupLeaseHandlers } from './ipc/leases';
import { setupReservationHandlers } from './ipc/reservations';
import { setupLocationHandlers } from './ipc/locations';
import { setupInsuranceHandlers } from './ipc/insurance';
import { setupStockAlertHandlers } from './ipc/stockAlerts';
import { setupApprovalHandlers } from './ipc/approvals';
import { startQRServer, stopQRServer } from './server/qrServer';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let splashWindow: BrowserWindow | null = null;
let mainWindow: BrowserWindow | null = null;

const createSplashWindow = (): BrowserWindow => {
  const splash = new BrowserWindow({
    width: 500,
    height: 400,
    transparent: true,
    frame: false,
    alwaysOnTop: true,
    resizable: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // __dirname is .webpack/main, splash.html is copied to .webpack/main/src/splash.html
  const splashPath = join(__dirname, 'src', 'splash.html');
  console.log('Loading splash screen from:', splashPath);

  splash.loadFile(splashPath).catch(err => {
    console.error('Failed to load splash screen:', err);
    // Close splash if it fails to load
    splash.close();
  });

  splash.center();

  return splash;
};

const createMainWindow = (): BrowserWindow => {
  // Create the browser window.
  const window = new BrowserWindow({
    height: 900,
    width: 1400,
    minHeight: 700,
    minWidth: 1200,
    show: false, // Don't show until ready
    frame: false, // Remove default frame for custom titlebar
    titleBarStyle: 'hidden',
    trafficLightPosition: { x: 10, y: 10 }, // Position for macOS traffic lights
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open DevTools only in development
  if (process.env.NODE_ENV === 'development') {
    window.webContents.openDevTools();
  }

  // Show window when ready
  window.once('ready-to-show', () => {
    if (splashWindow && !splashWindow.isDestroyed()) {
      console.log('Closing splash window');
      splashWindow.close();
      splashWindow = null;
    }
    window.show();
    console.log('Main window shown');
  });

  return window;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  // Show splash screen immediately
  splashWindow = createSplashWindow();

  // Safety timeout to close splash after 5 seconds max
  const splashTimeout = setTimeout(() => {
    if (splashWindow && !splashWindow.isDestroyed()) {
      console.log('Splash timeout - closing splash window');
      splashWindow.close();
      splashWindow = null;
    }
  }, 5000);

  try {
    // Initialize database while splash is showing
    await initDatabase();
    console.log('Database initialized successfully');

    setupCategoryHandlers();
    setupAssetHandlers();
    setupCustomFieldHandlers();
    setupInventoryItemHandlers();
    setupAssignmentHandlers();
    setupActivityLogHandlers();
    setupMaintenanceHandlers();
    setupSettingsHandlers();
    setupInventoryTransactionHandlers();
    setupBusinessProfileHandlers();
    setupCategoryPreferenceHandlers();
    setupQRCodeHandlers();
    setupFilterPresetHandlers();
    setupAuthHandlers();
    setupAttachmentHandlers();
    setupBarcodeHandlers();
    setupLeaseHandlers();
    setupReservationHandlers();
    setupLocationHandlers();
    setupInsuranceHandlers();
    setupStockAlertHandlers();
    setupApprovalHandlers();
    console.log('IPC handlers registered');

    // Start automatic database optimization scheduler
    scheduleAutomaticOptimization();
    console.log('Database optimization scheduler started');

    // Start QR code HTTP server for mobile viewing
    startQRServer();
    console.log('QR code HTTP server started');

    // Small delay to ensure splash is visible
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Create main window (splash will close when main window is ready)
    mainWindow = createMainWindow();

    // Clear the timeout since we're handling splash close properly
    clearTimeout(splashTimeout);
  } catch (error) {
    console.error('Failed to initialize app:', error);
    clearTimeout(splashTimeout);
    if (splashWindow && !splashWindow.isDestroyed()) {
      splashWindow.close();
    }
    app.quit();
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  stopQRServer();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindow = createMainWindow();
  }
});

// Window control IPC handlers
ipcMain.on('window-minimize', () => {
  const win = BrowserWindow.getFocusedWindow();
  if (win) win.minimize();
});

ipcMain.on('window-maximize', () => {
  const win = BrowserWindow.getFocusedWindow();
  if (win) {
    if (win.isMaximized()) {
      win.unmaximize();
    } else {
      win.maximize();
    }
  }
});

ipcMain.on('window-close', () => {
  const win = BrowserWindow.getFocusedWindow();
  if (win) win.close();
});

ipcMain.handle('window-is-maximized', () => {
  const win = BrowserWindow.getFocusedWindow();
  return win ? win.isMaximized() : false;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
