name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  backend:
    name: Backend - Maven build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -q -DskipTests package

  frontend:
    name: Frontend - Node build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund
      - name: Build frontend
        run: npm run build
      - name: Verify build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder not found after build"
            exit 1
          fi
          ls -la dist/
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E smoke tests
        run: npm run test:e2e -- --reporter=line
